config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout"},
             controllers: { omniauth_callbacks: "omniauth_callbacks"}
  root to: "home#index"
  get 'about' => "home#about"
  resources :friends, :only => [:index, :show] do
    member do
      get 'event/:word' => 'event#show'
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :tweets, ->{order 'created_at desc'}
  def increment
    self.count = self.count + 1
    self.save
  end
end

app/models/event_dictionary.rb
class EventDictionary < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  has_many :events,  -> { order 'count desc' }
  def to_param
    return username.parameterize
  end
  def self.find(key)
    return find_by_username(key)
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to  :event
end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]
  validates :username, presence: true, uniqueness: true

  def self.from_omniauth(auth)
    # providerとuidでUserレコードを取得する
    # 存在しない場合は、ブロック内のコードを実行して作成する
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.new(username: auth.info.nickname,
                      provider: auth.provider,
                      uid: auth.uid,
                      email: User.create_unique_email,
                      password: Devise.friendly_token[0,20],
                      oauth_token: auth.credentials.token,
                      oauth_token_secret: auth.credentials.secret
                     )
      #user.skip_confirmation!
      user.save
    end
    user
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
  def password_required?
    super && provider.blank?
  end
  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.create_unique_email
    User.create_unique_string + "@example.com"
  end

  def client
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['TW_CONS_KEY']
      config.consumer_secret     = ENV['TW_CONS_SECRET_KEY']
      config.access_token        = self.oauth_token
      config.access_token_secret = self.oauth_token_secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    friends_path
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def show
    @text = params["word"]
    @friend = Friend.find(params["id"])
    @event = Event.where(friend_id: @friend.id, name: @text).first
    @photos = []
    @photos_url = []
    search(@text)["photos"]["photo"].each do |photo|
      @photos.push(flickr_source_url(photo))
      @photos_url.push(flickr_photo_url(photo))
    end
  end
end
private
def search(text)
  res = RestClient.get 'https://api.flickr.com/services/rest', {:params => {:method => 'flickr.photos.search', :api_key => ENV['FL_CONS_KEY'], :text => text, :format => 'json', :sort => 'relevance', :per_page => '10'}}
  res.slice!(0,14)
  res.slice!(-1,1)
  JSON.parse(res)
end

def flickr_source_url(p)
  "http://farm#{p['farm']}.staticflickr.com/#{p['server']}/#{p['id']}_#{p['secret']}.jpg"
end
def flickr_photo_url(p)
  "https://www.flickr.com/photos/#{p['owner']}/#{p['id']}"
end

app/controllers/friends_controller.rb
# coding: utf-8
class FriendsController < ApplicationController
  before_action :authenticate_user!
  before_action :friend_of_current_user, :only => [:show]
  def index
    ids = current_user.client.friend_ids(current_user.username)
    @friends = current_user.client.users(ids.take(39))
  end

  def show
    @friend = Friend.find(params[:id])
    
    if @friend
      if @friend.status == "analyzed"
        @events = @friend.events.take(10)
      end
    else
      @friend = Friend.new(username: params[:id])
      @friend.save
      AnalyzeJobJob.perform_later(@friend.id,current_user.id)
    end
  end
  private
  def analyze(friend,current_user)
    friend_id = friend.id
    nm = Natto::MeCab.new
    tweets = current_user.client.user_timeline(friend.username, {count: 200})
    tweets.each do |tweet|
      nm.parse(tweet.full_text){|word|
        if word.feature.split(',')[0] == "名詞" &&
           EventDictionary.where(text: word.surface).first
          if event = Event.where(friend_id: friend_id, name: word.surface).first
            event.increment
            t = Tweet.new(event_id: event.id, text: tweet.full_text, url: tweet.uri, time: tweet.created_at)
            t.save
          else
            event = Event.new(friend_id: friend_id, name: word.surface, count: 1)
            event.save
            t = Tweet.new(event_id: event.id, text: tweet.full_text, url: tweet.uri, time: tweet.created_at)
            t.save
          end
        end
      }
    end
    @events = friend.events.take(10)
    @events.each do |event|
      unless event.image_url
        image_url = flickr_url(search(event.name)["photos"]["photo"][0])
        event.image_url = image_url
        event.save
      end
    end
    friend.status = "analyzed"
    friend.save
  end
  def search(text)
    res = RestClient.get 'https://api.flickr.com/services/rest', {:params => {:method => 'flickr.photos.search', :api_key => ENV['FL_CONS_KEY'], :text => text, :format => 'json', :sort => 'relevance', :per_page => '10'}}
    res.slice!(0,14)
    res.slice!(-1,1)
    JSON.parse(res)
  end
  def flickr_url(p)
    "http://farm#{p['farm']}.staticflickr.com/#{p['server']}/#{p['id']}_#{p['secret']}.jpg"
  end
  def friend_of_current_user
    true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  def show
  end
end

app/controllers/omniauth_callbacks_controller.rb
# coding: utf-8
class OmniauthCallbacksController < ApplicationController
  def all
    # profiderとuidでuserレコードを検索。存在しなければ、新たに作成する
    user = User.from_omniauth(request.env["omniauth.auth"])
    # userレコードが既に保存されているか
    if user.persisted?
      # ログインに成功
      flash.notice = "ログインしました!!"
      sign_in_and_redirect user
    else
      # ログインに失敗し、サインイン画面に遷移
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/event/show.html.erb
<div class="l-wrapper">
  <div class="header clearfix">
	<%= image_tag "cocoyan_logo_long", class: "logo"%>
	<div class="title"><%= @text %></div>
	<div class="control"></div>
	<div class="back">
	  <%= link_to image_tag('back'), :back%>
	</div>
  </div>
  <div class="main">
	<div class="info_box">
	  <a href="https://www.google.co.jp/search?q=<%=@text %>"><%= image_tag('cocoyan_search') %>『<%= @text %>』</a>
	</div>
	<% @event.tweets.each_with_index do |tweet, i| %>
	  <div class="tweet">
		<span class="tweet_username">@<%= @friend.username%></span><br>
		<%= tweet.text %><br>
		<span class="tweet_time"><%= link_to tweet.time.strftime("%Y %m/%d %H:%M"), tweet.url%></span><br>
	  </div>
	<% end %>
	<% @photos.take(3).each_with_index do |photo, i| %>
	  <div class="l-row">
		<div class="l-grid">
		  <div class="rect_place" style="background:url(<%= photo %>); background-size: cover;">
			<%= link_to "", @photos_url[i], class: "photo_link"%>
		  </div>
		</div>
	  </div>
	<% end %>
	
  </div>
  <div class="footer">
  <%= link_to 'ログアウト', destroy_user_session_path, :method => :delete, class: "logout" %>
</div>
</div>

app/views/friends/_analyzing.html.erb
<div class="l-wrapper">
  <div class="analyzing">
	<div class="charbox clearfix">
	  <span class="char">解</span>
	  <span class="char">析</span>
	  <span class="char">中</span>
	</div>
  </div>
  <%= image_tag "cocoyan_log3.png", class: "analyzing_logo"%>
</div>
<script>
function jump(){
	for(var i= 0; i < 3; i++){
		$(".char").delay(i+200).eq(i).animate({
			marginTop: "0px",
		}, 250, "linear").animate({
			marginTop: "-10px",
		}, 150, "linear").animate({
			marginTop: "0px",
		}, 250, "linear");
	}
	setTimeout("jump()",1000);
}
$(function(){
	setTimeout("jump()",1);
	setTimeout(function(){
	location.reload();
	},5000);
});
</script>

app/views/friends/_result.html.erb
<div class="l-wrapper">
  <div class="header clearfix">
	<%= image_tag "cocoyan_logo_long", class: "logo"%>
	<div class="title"><%= @friend.username %></div>
	<div class="control"></div>
	<div class="back">
	  <%= link_to image_tag('back'), friends_path%>
	</div>
  </div>
  <div class="main">
	<% @events.each_with_index do |event, i| %>
	  <% if i == 0 %>
		<div class="l-row clearfix">
		  <div class="l-grid">
			<div class="place" style="background:url(<%= event.image_url%>); background-size:cover">
			  <div class="title"><%= event.name%></div>
			  <div class="circle_big">
				<div class="inner">
				  <%= event.count%>
				</div>
			  </div>
			  <%= link_to "", "/friends/#{@friend.username}/event/#{event.name}"%>
			</div>
		  </div>
		</div>
	  <% else %>
		<% if (i % 2) == 1 %>
		  <div class="l-row clearfix">
		<% end %>
		<div class="l-grid-1-2">
		  <div class="place"  style="background:url(<%= event.image_url%>); background-size: cover;">
			<div class="title"><%= event.name%></div>
			<div class="circle_small">
			  <div class="inner">
				<%= event.count %>
			  </div>
			</div>
			<%= link_to "", "/friends/#{@friend.username}/event/#{event.name}"%>
		  </div>
		</div>
		<% if(i % 2) == 0 && i != 0%>
		  </div>
		<% end %>
		<% if(i % 2) != 0 && @events.length == i+1 %>
  </div>
        <% end %>
	  <% end %>
	<% end %>
</div>
<div class="footer">
  <%= link_to 'ログアウト', destroy_user_session_path, :method => :delete, class: "logout" %>
</div>
</div>

app/views/friends/index.html.erb
<div class="l-wrapper">
  <div class="header clearfix">
	<%= image_tag "cocoyan_logo_long", class: "logo"%>
	<div class="title">ユーザーを選択</div>
	<div class="control"></div>
	<div class="back">
	  <%= link_to image_tag('back'), root_path%>
	</div>
  </div>
  <div class="main">
	<% @friends.each_with_index do |friend, i| %>
	  <% if (i % 3) == 0 %>

		<div class="friends">
	  <% end %>
	  <div class="friend">
		<div class="inner">
		            <%= link_to image_tag(friend["profile_image_url"]) , friend_path(friend.username)%>
		</div>
	  </div>
	  <% if (i % 3) == 2%>
		</div>
	  <% end %>
	  <% if (i % 3) != 2 && @friends.length == i+1%>
  </div>
      <% end %>
	<% end %>
</div>
<div class="footer">
  <%= link_to 'ログアウト', destroy_user_session_path, :method => :delete, class: "logout" %>
</div>
</div>

app/views/friends/show.html.erb
<% if @friend.status == "analyzing" %>
  <%= render 'friends/analyzing' %>
<% else %>
  <%= render 'friends/result'%>
<% end %>

app/views/home/about.html.erb
<div class="l-wrapper">
  <div class="header clearfix">
	<%= image_tag "cocoyan_logo_long", class: "logo"%>
	<div class="title">このアプリについて</div>
	<div class="control"></div>
	<div class="back">
	  <%= link_to image_tag('back'), root_path%>
	</div>
  </div>
  <h1 class="desc_h">どんなアプリ?</h1>
  <div class="description2" style="text-align:center;">
	"COCO-YAN"は、<br>「実はここ、行きたかったんでしょ？」を提供できるWebアプリケーションです。<br>
	Twitterを使用する知りたい特定ユーザーの今までのつぶやきを解析を行い、その人が行きたいと思っていた場所を表示します。<br>
	それを見ることによってその人に対して行きたいと思う場所へと誘ったりして喜ばせることができます。<br>
  </div>
  <h1 class="desc_h">解析の仕組み</h1>
  <div class="diagram">
	<%= image_tag "c1"%>
	<%= image_tag "c2"%>
  </div>
  <div class="description2" style="text-align:center;">
	世界中の呟きから行きたい対象となる単語のリスト(辞書データ)を作成します。<br>
	「◯◯に行きたい」「◯◯行きたい」といったつぶやきの◯◯を収集し、辞書データを作成しました。
  </div>
  <div class="diagram">
	<%= image_tag "c3"%>
	<%= image_tag "c4"%>
  </div>
  <div class="description2" style="text-align:center;">
	解析対象のユーザの呟きから、辞書データに存在する単語を含むものを抽出します。
  </div>
  <h1 class="desc_h">クレジット</h1>
  <div class="description2" style="text-align:center;">
	本ソフトウェアは以下のソフトウェアを含んでいます<br>
	rails<br>
	sqlite3<br>
	sass-rails<br>
	uglifier<br>
	coffee-rails<br>
	jquery-rails<br>
	turbolinks<br>
	jbuilder<br>
	sdoc<br>
	byebug<br>
	web-console<br>
	spring<br>
	devise<br>
	omniauth-twitter<br>
	dotenv-rails<br>
	twitter<br>
	faraday<br>
	natto<br>
	rest-client<br>
	resque<br>
	mongo<br>
	mongoid<br>
	pg<br>
	rails_12factor<br>
  </div>
</div>

app/views/home/index.html.erb
<div class="l-wrapper">
  <%= image_tag "cocoyan_log3.png", class: "logo"%>
  <div class="select_sns">
	Login
  </div>
  <div class="sns_buttons">
	<div class="sns_button">
	  <div class="inner">
		<%= link_to image_tag('TwitterLogo_white', class: "twitter"), user_omniauth_authorize_path(:twitter) %>
	  </div>
	</div>
  </div>
  <div class="description" style="text-align:center;">
	"COCO-YAN" は<br>Twitterから友達が<br>行きたかった場所を<br>一緒に探してくれます
  </div>
  <div class="footer">
	<a href="https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fcocoyan.herokuapp.com%2F&ref_src=twsrc%5Etfw&text=COCO-YAN&tw_p=tweetbutton&url=https%3A%2F%2Fcocoyan.herokuapp.com%2F" class="tweet_btn">ツイート</a>
	<a href="./about" class="about_link">アプリについて</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CocoYan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
</head>
<body>

<%= yield %>

</body>
</html>